# This allows krr pod to access prometheus data.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: krr-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
roleRef:
  kind: ClusterRole
  name: view  # 'view' gives read-only access to resources
  apiGroup: rbac.authorization.k8s.io